# -*- coding: utf-8 -*-
"""Run-predict.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15RE9RbonFIgRyU9s6Xr9Gez9x9b341Lc

###Custom built/trained model to predict run times based on previous week of running and goal distance

##Imports
"""

import pandas as pd
import numpy as np
import tensorflow as tf
from tensorflow.keras import layers, models
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split

"""##Data Load"""

# Load and sort your dataset
df = pd.read_csv("runs.csv", parse_dates=["start_date"])
df = df.sort_values("start_date").reset_index(drop=True)

# --- Handle missing heart rate ---
df["average_heartrate"] = df["average_heartrate"].fillna(155)

# --- Compute derived features ---
# Pace (min/mile)
df["pace_min_per_mile"] = (df["moving_time"]) / (df["distance"])  # moving_time in seconds, distance in miles
df["pace_min_per_mile"] = df["pace_min_per_mile"].replace([np.inf, -np.inf], np.nan)

# Drop any rows where pace couldn’t be calculated
df = df.dropna(subset=["pace_min_per_mile"])

# Days since last run
df["days_since_last_run"] = df["start_date"].diff().dt.total_seconds() / (3600 * 24)
df["days_since_last_run"] = df["days_since_last_run"].fillna(1.0)  # assume 1 day gap if missing

# 7-day rolling total distance (fatigue / training load)
df["rolling_7d_distance"] = df["distance"].rolling(window=7, min_periods=1).sum()


# Select relevant features
features = ["distance", "average_speed", "average_heartrate", "total_elevation_gain", "days_since_last_run", "rolling_7d_distance"]
target_cols = ["pace_min_per_mile"]

print(df.head(10))

"""##Create Sliding Windows"""

SEQ_LEN = 7  # number of past runs used for prediction

X_seq, X_plan, y = [], [], []

for i in range(SEQ_LEN, len(df)):
    # past 7 runs as input sequence
    past_week = df.iloc[i-SEQ_LEN:i][["distance", "average_speed", "total_elevation_gain", "days_since_last_run", "rolling_7d_distance"]].values
    next_run = df.iloc[i]

    # planned run features
    desired_distance = next_run["distance"]
    desired_hr = next_run["average_heartrate"]

    # targets (what we’re predicting)
    target = next_run[["pace_min_per_mile"]].values

    X_seq.append(past_week)
    X_plan.append([desired_distance, desired_hr])
    y.append(target)

# convert to numpy arrays
X_seq = np.array(X_seq)
X_plan = np.array(X_plan)
y = np.array(y)

print("Sequence input shape:", X_seq.shape)
print("Planned input shape:", X_plan.shape)
print("Target shape:", y.shape)

"""##Normalize Data"""

from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split

# Create scalers
seq_scaler = StandardScaler()
plan_scaler = StandardScaler()
target_scaler = StandardScaler()

# Fit + transform
X_seq_flat = X_seq.reshape(-1, X_seq.shape[2])
X_seq_scaled = seq_scaler.fit_transform(X_seq_flat).reshape(X_seq.shape)
X_plan_scaled = plan_scaler.fit_transform(X_plan)
y_scaled = target_scaler.fit_transform(y)

# Split train/test chronologically (no shuffle)
X_seq_train, X_seq_test, X_plan_train, X_plan_test, y_train, y_test = train_test_split(
    X_seq_scaled, X_plan_scaled, y_scaled, test_size=0.2, shuffle=False
)

print(X_seq_train.shape, y_train.shape)

"""##Training"""

import tensorflow as tf
from tensorflow.keras import layers, models

SEQ_LEN = X_seq_train.shape[1]

# --- Sequence input (past 7 runs) ---
seq_input = layers.Input(shape=(SEQ_LEN, 5))
x = layers.LSTM(32, return_sequences=False)(seq_input)
x = layers.Dense(16, activation="relu")(x)
x = layers.Dropout(0.4)(x)  # helps prevent overfitting

# --- Planned run input (desired distance + HR) ---
plan_input = layers.Input(shape=(2,))
p = layers.Dense(8, activation="relu")(plan_input)

# --- Merge both ---
merged = layers.Concatenate()([x, p])
output = layers.Dense(1, activation="linear")(merged)
# z = layers.Dense(32, activation="relu")(merged)
# z = layers.Dropout(0.4)(z)

# # --- Output: predict pace + moving_time ---
# output = layers.Dense(1, activation="linear")(z)

# --- Build & compile ---
model = models.Model(inputs=[seq_input, plan_input], outputs=output)
model.compile(optimizer="adam", loss="mae")

model.summary()

from tensorflow.keras.utils import plot_model

plot_model(
    model,
    to_file="model_structure.png",
    show_shapes=True,
    show_layer_names=True,
    expand_nested=True,
    dpi=100
)

"""##Fit model"""

history = model.fit(
    [X_seq_train, X_plan_train],
    y_train,
    validation_data=([X_seq_test, X_plan_test], y_test),
    epochs=30,
    batch_size=32,
    verbose=1
)

import matplotlib.pyplot as plt

plt.figure(figsize=(8,4))
plt.plot(history.history["loss"], label="Train Loss")
plt.plot(history.history["val_loss"], label="Validation Loss")
plt.title("Training vs Validation Loss (MAE)")
plt.xlabel("Epoch")
plt.ylabel("Mean Absolute Error (scaled units)")
plt.legend()
plt.show()

"""##Evaluation"""

y_pred_scaled = model.predict([X_seq_test, X_plan_test])
y_pred = target_scaler.inverse_transform(y_pred_scaled)
y_true = target_scaler.inverse_transform(y_test)

plt.figure(figsize=(10,6))
plt.subplot(2,1,1)
plt.plot(y_true[:,0], label="Actual Pace (min/mile)")
plt.plot(y_pred[:,0], label="Predicted Pace")
plt.legend()
plt.title("Pace Prediction")

# Get your most recent 7 runs
recent_seq = df.iloc[-7:][["distance", "average_speed", "total_elevation_gain", "days_since_last_run", "rolling_7d_distance"]].values
recent_seq_scaled = seq_scaler.transform(recent_seq).reshape(1, 7, 5)

# Define your planned run
desired_distance = 26.2 # miles
desired_hr = 153
planned_scaled = plan_scaler.transform([[desired_distance, desired_hr]])

# Predict
pred_scaled = model.predict([recent_seq_scaled, planned_scaled])
pred = target_scaler.inverse_transform(pred_scaled)[0]
predicted_pace= pred

print(f"🏃 Predicted pace for {desired_distance}: {predicted_pace} min/mile")



# Save the model
model.save('running_pace_model.h5')

"""You can download the saved model file (`running_pace_model.h5`) by clicking on the folder icon on the left sidebar, navigating to the file, right-clicking on it, and selecting "Download"."""